project:
  name: quickstart-salesforce-health-cloud-virtual-care
  owner: quickstart-eng@amazon.com
  template: templates/salesforce-health-cloud-virtual-care.template.yaml
  parameters:
    SalesforceUsername: override
    SalesforcePassword: override
    SalesforceOAuthClientID: override
    SalesforceOAuthClientSecret: override
    SalesforceAuthorizationEndpoint: override
    SalesforcePlatformEventEndpoint: override
    SalesforcePlatformEventEndpointRateLimit: 5
    DlqAlarmEmail: override
    IamUserName: $[taskcat_genpass_8A]
    IamPassword: $[taskcat_genpass_128S]
    IamGroupName: $[taskcat_genpass_8A]
  regions:
    - ap-southeast-1
    - eu-central-1
    - us-east-1
    - us-west-2
tests:
  default:
    regions:
      - us-east-1
